/*
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.releans.platform.controllers;

import android.support.test.InstrumentationRegistry;
import android.support.test.runner.AndroidJUnit4;
import android.test.suitebuilder.annotation.LargeTest;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.releans.platform.models.*;
import com.releans.platform.exceptions.*;
import com.releans.platform.APIHelper;
import com.releans.platform.Configuration;
import com.releans.platform.testing.TestHelper;
import com.releans.platform.controllers.BalanceController;
import com.releans.platform.controllers.syncwrapper.APICallBackCatcher;

import com.fasterxml.jackson.core.type.TypeReference;

@RunWith(AndroidJUnit4.class)
@LargeTest
public class BalanceControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static BalanceController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getBalance();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Get your available balance
     * @throws Throwable
     */
    @Test
    public void testBalance() throws Throwable {
        // Parameters for the API call
        String accept = "text/plain";

        // Set callback and perform API call
        Response2002 result = null;
        APICallBackCatcher<Response2002> response = new APICallBackCatcher<Response2002>();
        controller.setHttpCallBack(httpResponse);
        controller.getBalanceAsync(accept, response);
        result = response.getResult();

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", TestHelper.nullString);
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders(), true));

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response body does not match exactly",
                "{\"balance\":100}", 
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()));
    }

}
